version: '3'

services:
  postgres:
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=market_admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market_data
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
  ingestion:
    environment:
      - DB_URI=postgresql://market_admin:postgres@postgres:5432/market_data
  broker:
    environment:
      - POSTGRES_USER=market_admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market_data
      - DB_URI=postgresql://market_admin:postgres@postgres:5432/market_data
  batch:
    environment:
      - POSTGRES_USER=market_admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market_data 