apiVersion: v1
kind: Secret
metadata:
  name: fmp-secrets
type: Opaque
data:
  FMP_API_KEY: <base64_encoded_fmp_api_key>
  POSTGRES_PASSWORD: <base64_encoded_postgres_password>
---
apiVersion: v1
kind: Secret
metadata:
  name: telegram-secrets
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: <base64_encoded_telegram_bot_token>
