apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: "market_admin"
  POSTGRES_PASSWORD: "change-me-in-production"

---
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
type: Opaque
stringData:
  FMP_API_KEY: "your-api-key-here"
  TELEGRAM_BOT_TOKEN: "your-telegram-bot-token-here"
  JWT_SECRET: "change-this-to-a-secure-random-string-in-production"

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-credentials
type: Opaque
stringData:
  PROMETHEUS_BASIC_AUTH_USER: "prometheus"
  PROMETHEUS_BASIC_AUTH_PASSWORD: "change-me-in-production"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "change-me-in-production"
